SERVER_HOST="k3d-machine"
HOME=ENV['HOME']

Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora33"
  config.vm.box_check_update = false
  config.vm.define SERVER_HOST do |server|
    server.vm.hostname = SERVER_HOST
    server.vm.synced_folder ".", "/vagrant", type: "rsync"
    server.vm.provider :virtualbox do |vb|
      vb.name = SERVER_HOST
      vb.cpus   = 4
      vb.memory = 4096
    end

    server.vm.provision "start provissiong machine", type: "shell", path: "prov.sh", privileged: false
    
  end

end

