SERVER_HOST="k3d-machine"
HOME=ENV['HOME']

Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora38"
  config.vm.box_check_update = false
  config.ssh.insert_key = false
  config.ssh.password = "vagrant"
  config.vm.network "forwarded_port", guest: 8000, host: 8080
  config.vm.define SERVER_HOST do |server|
    server.vm.hostname = SERVER_HOST
    server.vm.provider :virtualbox do |vb|
      vb.name = SERVER_HOST
      vb.cpus   = 4
      vb.memory = 4096
    end

    server.vm.provision "start provissiong machine", type: "shell", path: "prov.sh", privileged: false
    
  end

end

