- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Install k3s prequisite packages
  ansible.builtin.dnf:
    name:
      - kernel-modules-extra
      - iptables
    state: present

- name: Provision k3s server
  ansible.builtin.import_tasks: server.yml
  when: k3s_role == "server"

- name: Provision k3s agent
  ansible.builtin.import_tasks: agent.yml
  when: k3s_role == "agent"
