SERVER_IP   = "192.168.56.115"
SERVER_HOST = "nhayounS"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"
  config.vm.box_check_update = false

  # --- Server Node ---
  config.vm.define SERVER_HOST do |server|
    server.vm.hostname = SERVER_HOST
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.synced_folder ".", "/vagrant", type: "rsync"

    server.vm.provider :libvirt do |lv|
      lv.uri    = "qemu:///system"
      lv.cpus   = 2
      lv.memory = 1024
    end
    #1. Base Dependencies (Run First)
    server.vm.provision "install_deps", type: "shell", path: "scripts/deps.sh"
    server.vm.provision "setup_modules", type: "shell", path: "scripts/kernel-modules.sh"
    server.vm.provision "install_server_k3s",  type: "shell", path: "scripts/server.sh"
  end

end

