SERVER_IP   = "192.168.56.110"
AGENT_IP    = "192.168.56.111"
SERVER_HOST = "member1S"
AGENT_HOST = "member2SW"


Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  config.vm.box_check_update = false

  # --- Server Node ---
  config.vm.define SERVER_HOST do |server|
    server.vm.hostname = SERVER_HOST
    server.vm.network "private_network", ip: SERVER_IP

    server.vm.synced_folder ".", "/vagrant", type: "virtiofs"

    server.vm.provider :libvirt do |lv|
      lv.uri    = "qemu:///system"
      lv.cpus   = 2
      lv.memory = 2048

      lv.memorybacking :access, :mode => "shared"
    end
    #1. Base Dependecies (Run First)
    server.vm.provision "install_deps", type: "shell", path: "scripts/deps.sh"
    #2. K3s setup (server)
    server.vm.provision "setup_cluster",  type: "shell", path: "scripts/server.sh", run: "never"
  end

  # --- Agent/Worker Node ---
  config.vm.define AGENT_HOST do |agent|
    agent.vm.hostname = AGENT_HOST
    agent.vm.network "private_network", ip: AGENT_IP

    agent.vm.synced_folder ".", "/vagrant", type: "virtiofs"
    agent.vm.provider :libvirt do |lv|
      lv.uri    = "qemu:///system"
      lv.cpus   = 2
      lv.memory = 2048
      lv.memorybacking :access, :mode => "shared"
    end
    #1. Base Dependecies (Run First)
    agent.vm.provision "install_deps", type: "shell", path: "scripts/deps.sh"
    #2. Cluster Setup (agent)
    agent.vm.provision "setup_cluster", type: "shell", path: "scripts/agent.sh", run: "never"
  end
end


