Vagrant.configure("2") do |config|
  config.vm.define "member1S" do |server|
    server.vm.box = "generic/fedora28"
    server.vm.box_version = "4.3.12"
#    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "member1S"
    server.vm.provider :libvirt do |libvirt|
      libvirt.uri = "qemu:///system"
      libvirt.cpus = 1
      libvirt.memory = 512
    end
    server.vm.provision "shell", inline: <<-SHELL
        set -e
        dnf update -y
      SHELL
    end
end
